stages:
  - lint
  - build
  - benchmark
  - doc

lint:
  stage: lint
  image: ocaml/opam2:4.09
  before_script:
    - sudo apt-get install m4 -y
    - eval $(opam env)
    - opam update
    - opam install ocamlformat.0.14.1 -y
  script:
    - ocamlformat --check src/*.ml*
    #- ocamlformat --check test/*.ml*

.build-test: &build_definition
  stage: build
  before_script:
    # Always update system package manager + setup OPAM env
    - sudo apt-get update && sudo apt-get upgrade -y
    - eval $(opam env)
    - opam update
    - opam depext -i -y zarith
  script:
    - opam install --deps-only --with-test -y .
    # Install the package
    - opam install . -y
    # Run tests
#    - dune build @runtest
    # js_of_ocaml compatibility
#    - opam install js_of_ocaml js_of_ocaml-compiler js_of_ocaml-ppx zarith_stubs_js
#    - dune build js
#    - cp _build/default/js/FiniteField.js js/test
#    - node js/test/test_js.js

build-ocaml-4.07:
  <<: *build_definition
  image: ocaml/opam2:4.07

build-ocaml-4.08:
  <<: *build_definition
  image: ocaml/opam2:4.08

build-ocaml-4.09:
  <<: *build_definition
  image: ocaml/opam2:4.09

build-ocaml-4.10:
  <<: *build_definition
  image: ocaml/opam2:4.10

.benchmark: &benchmark_definition
  stage: benchmark
  before_script:
    # Always update system package manager + setup OPAM env
    - sudo apt-get update && sudo apt-get upgrade -y
    - eval $(opam env)
    - opam update
    - opam depext -i -y zarith
    - opam install -y .
  script:
    # Benchmark
    - opam install core_bench.v0.12.0
    - dune build benchmark/bench_ff.exe

benchmark-ocaml-4.07:
  <<: *benchmark_definition
  image: ocaml/opam2:4.07

benchmark-ocaml-4.08:
  <<: *benchmark_definition
  image: ocaml/opam2:4.08

benchmark-ocaml-4.09:
  <<: *benchmark_definition
  image: ocaml/opam2:4.09

generate-documentation:
  stage: doc
  image: ocaml/opam2:4.09
  before_script:
    - sudo apt-get install m4 -y
    - eval $(opam env)
    - opam update
    - opam depext -i -y zarith
    - opam install dune odoc
    - opam install -y .
  script:
    - dune build @doc
